"""Intent labels for API compatibility. Execution plans are built at runtime by the orchestrator."""

from enum import Enum


class IntentType(str, Enum):
    """Legacy intent names; new commands use intent='ORCHESTRATED' with runtime tasks."""

    GENERAL_CHAT = "GENERAL_CHAT"
    OPEN_APP = "OPEN_APP"
    CLOSE_APP = "CLOSE_APP"
    HANDLE_ASSIGNMENTS = "HANDLE_ASSIGNMENTS"
    CHECK_ASSIGNMENTS = "CHECK_ASSIGNMENTS"
    DO_ASSIGNMENT = "DO_ASSIGNMENT"
    START_PROJECT = "START_PROJECT"
    CREATE_PROJECT = "CREATE_PROJECT"
    RESUME_PROJECT = "RESUME_PROJECT"
    STUDY_MODE = "STUDY_MODE"
    FOCUS_MODE = "FOCUS_MODE"
    SEARCH_WEB = "SEARCH_WEB"
    OPEN_WEBSITE = "OPEN_WEBSITE"
    PLAY_MUSIC = "PLAY_MUSIC"
    STOP_MUSIC = "STOP_MUSIC"
    SYSTEM_CONTROL = "SYSTEM_CONTROL"
    FILE_OPERATION = "FILE_OPERATION"
    FETCH_TECH_NEWS = "FETCH_TECH_NEWS"
    FETCH_WORLD_NEWS = "FETCH_WORLD_NEWS"
    WATCH_VIDEO = "WATCH_VIDEO"
    MORNING_RITUAL = "MORNING_RITUAL"
    ORCHESTRATED = "ORCHESTRATED"
    UNKNOWN = "UNKNOWN"
